config/routes.rb
Teamvillage::Application.routes.draw do

  devise_for :users
  resources :users, :except => [:new, :create]  do
    put 'block', :on => :member, :as => 'block'
  end

  resources :projects do 
    resources :tasks do
      put 'close', :on => :member, :as => 'close'
    end
  end

  root :to => 'users#user_tasks'

  # match 'm/:action/:id' => 'mailer#:action'

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		can [:read,:create,:user_tasks], :all
		
		user ||= User.new

		can [:update, :destroy], Project do |project|
			project.owner == nil or
			user.owner_of?(project)
		end

		can [:close, :destroy], Task do |task|
			user.owner_of?(task.project)
		end

		can :update, Task do |task|
			task.executer == nil or
			user.executer_of?(task) or
			user.owner_of?(task.project)
		end

		if user.role? :admin
				can [:update, :destroy], User 

				can [:block, :edit_roles], User do |edited_user|
					user != edited_user
				end
		else
			can [:update, :destroy], User do |updated_user|
				user == updated_user
			end
		end
	end
end

app/models/modules/Roles.rb
module Roles
  ROLES = %w[admin]


  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

	def roles
  	ROLES.reject { |r| ((self.roles_mask || 0) & 2**ROLES.index(r)).zero? }
	end

	def role?(role)
		roles.include? role.to_s
	end

end

app/models/modules/roles.rb
module Modules::Roles
  ROLES = %w[admin]


  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

	def roles
  	ROLES.reject { |r| ((self.roles_mask || 0) & 2**ROLES.index(r)).zero? }
	end

	def role?(role)
		roles.include? role.to_s
	end

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	belongs_to :owner, class_name: 'User'

	scope :owned_by, ->(user) { where owner_id:user }
	scope :executed_by, ->(user) { joins(tasks: :executer).where('users.id = ?', user).group('projects.id') }

	validates :name, presence: true, uniqueness: true

  def progress
  	self.tasks.average(:persentage)
  end

  def to_s
  	name || email
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :executer, class_name: 'User'
	belongs_to :project

	validates_inclusion_of :persentage, :in => 0..100

  symbolize :status , :in =>[:new, :assigned, :finished, :closed], default: :new, methods: true

  def close
    self.status = :closed
    self.persentage = 100
  end

  def to_s
  	name
  end
end

app/models/user.rb
require 'modules/roles'

class User < ActiveRecord::Base
  include Modules::Roles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, foreign_key: :owner_id

  def executing_tasks(project = nil)
    tasks = Task.where('executer_id = :user', user: self)
    tasks = tasks.where('project_id = :project',project: project) if project

    tasks
  end

  def owner_of?(project)
    project.try(:owner) == self
  end

  def executer_of?(task)
    task.try(:executer) == self
  end

  def self.send_status_mail
    select('id, name, email').each do |user|
      user.send_status_mail
    end
  end

  # does user owns the project or execute task
  def need_send_status_mail?
    Project.owned_by(self).count > 0 ||
    Project.executed_by(self).count.present?
  end

  def send_status_mail    
    UserMailer.status(self).deliver if need_send_status_mail?
  end



  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	before_filter :authenticate_user!, :banned?
	before_filter ->(role){ @role = current_user.roles.first if current_user}

  private
  
  def banned?
    if current_user.present? && current_user.blocked?
      sign_out current_user
      flash[:notice] = "This account has been blocked by admins"
      redirect_to new_user_session_path
      
    end
  end
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
	def status
		user = User.find params[:id]

		@name = user.name
  	@owned_projects = Project.owned_by(user).includes(:tasks)
  	@paricipate_projects = Project.executed_by(user).includes(:tasks) 
  	@paricipate_projects -= @owned_projects

  	render :file => 'user_mailer/status.html.haml', :layout => 'mail'
	end

	def send_status
		user = User.find params[:id]

		user.send_status_mail

		render nothing: true
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  load_and_authorize_resource

  responders :flash 
  respond_to :html, :json

  def index
    respond_with @projects
  end

  def show
    respond_with @project 
  end

  def new
    @project.owner = current_user
  end

  def edit
  end

  def create
    @project.save
    respond_with @project
  end

  def update
    @project.update_attributes(params[:project])
    respond_with @project
  end

  def destroy
    @project.destroy
    respond_with @project
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && resource.blocked?
      sign_out resource
      flash[:notice] = "This account has been blocked by admin"
      sign_in_path
    else
      super
    end
   end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource :project
  load_and_authorize_resource :task, through: :project

  responders :flash
  respond_to :html, :json

  def index
    respond_with @project, @tasks
  end

  def show
    respond_with @task 
  end

  def new
    init_form_collections
  end

  def edit
    init_form_collections
  end

  def create
    init_form_collections unless @task.save
    respond_with @task.project, @task
    # respond_to do |format|
    #   if @task.save
    #     format.html do 

    #       if @task.project
    #         redirect_to @task.project, notice: 'Task was successfully created.' 
    #       else
    #         redirect_to @task, notice: 'Task was successfully created.' 
    #       end
    #     end

    #     format.json { render json: @task, status: :created, location: @task }
    #   else
    #     init_form_collections
    #     format.html { render action: "new" }
    #     format.json { render json: @task.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    init_form_collections unless @task.update_attributes(params[:task])
    respond_with @task.project, @task
  end

  def destroy
    @task.destroy
    respond_with @task
  end

  def close
    @task.close
    init_form_collections unless @task.save
    respond_with @task
  end

  private

  def init_form_collections  
    @all_users = User.select 'id, name'
    @all_statuses = Hash[Task.get_status_values].values
    @all_statuses.delete :closed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  load_and_authorize_resource

  responders :flash
  respond_to :html, :json

  def index
    respond_with @users 
  end

  def show
    respond_with @user 
  end

  def edit
  end

  def update
    params[:user][:roles] ||= []
    @user.update_attributes(params[:user])
    respond_with @user
  end

  def destroy
    @user.destroy
    respond_with @user
  end

   def user_tasks
  	@viewed_tasks = current_user.executing_tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	def can_be_closed?(task)
		!task.closed? and can? :close, task
	end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Teamvillage
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .b-caption
      - if user_signed_in?
        .left-anchor
          = @role
        Signed in as 
        %span.user-name #{current_user.name}.
        =link_to 'Home', root_path
        =link_to 'Signed out', destroy_user_session_path
      - else
        =link_to 'Signed in', new_user_session_path
        or 
        =link_to 'Signed up', new_user_registration_path
    .b-main
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/layouts/mail.html.haml
%html
  %head
    %title Teamvillage
    = stylesheet_link_tag    "application", :media => "all"
  %body
    = yield

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    Owner
    %b= @project.owner
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1.b-title Listing projects

%table.b-data-table
  %tr
    %th Name
    %th{colspan: 3} Actions

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= link_to 'Show', project
      %td
        - if can? :update, project
          = link_to 'Edit', edit_project_path(project)
      %td
        - if can? :destroy, project
          = link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1.b-title New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%h1.b-title
  Project:
  = @project.name
%p
  %b Owner:
  = @project.owner

= render partial: 'tasks/tasks_table',locals: {tasks: @project.tasks}

%p
  = link_to 'Add Task', new_project_task_path(@project)
  \|
  - if can? :update, @project
    = link_to 'Edit', edit_project_path(@project)
    \|
  = link_to 'Back', projects_path

app/views/tasks/_form.html.haml
= form_for [@task.project, @task] do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    Project
    %b= @task.project
  .field
    = f.label :executer_id
    = f.collection_select(:executer_id, @all_users, :id, :name, :prompt => '') 
  .field
    = f.label :status
    = render partial: 'tasks/status_field', locals: {form: f, task: @task, all_statuses: @all_statuses}
  .field
    = f.label :persentage
    = f.number_field :persentage
  .field
    = f.label :description
    %br
    = f.text_area :description, size: '25x5'
   

  .actions
    = f.submit 'Save'

app/views/tasks/_status_field.html.haml
-if task.closed?
  %b= form.label task.status
-else
  = form.select :status, all_statuses

app/views/tasks/_tasks_table.html.haml
-# default show actions
- with_actions = true unless local_assigns.has_key? :with_actions

%table.b-data-table
  %thead
    %tr
      %th Name
      %th Executer
      %th Status
      %th Persentage
      %th Project
      - if with_actions
        %th{colspan: 4} Actions      
  %tbody
    - tasks.each do |task|
      %tr
        %td= task.name
        %td= task.executer
        %td= t(task.status)
        %td.number-column= "#{task.persentage} %"
        %td= task.project
        - if with_actions
          %td= link_to 'Show', [task.project, task]
          %td
            - if can_be_closed? task
              = link_to 'Close', close_project_task_path(task.project, task), method: :put
          %td 
            - if can? :update, task
              = link_to 'Edit', edit_project_task_path(task.project, task)
          %td
            - if can? :destroy, task
              = link_to 'Destroy', [task.project, task], method: :delete, data:  { confirm: 'Are you sure?' }

app/views/tasks/edit.html.haml
%h1.b-title Editing task

= render 'form'

= link_to 'Show', [@task.project, @task]
\|
= link_to 'All Project Tasks', project_tasks_path(@task.project)

app/views/tasks/index.html.haml
%h1.b-title Listing tasks

= render partial: 'tasks/tasks_table',locals: {tasks: @tasks}

%br

= #link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1
  New task

= render 'form'
%p
  = link_to 'All project tasks', project_tasks_path(@task.project)

app/views/tasks/show.html.haml
%p
  %b Name:
  = @task
%p
  %b User:
  = @task.executer
%p
  %b Status:
  = t(@task.status)
%p
  %b Persentage:
  = @task.persentage
%p
  %b Project:
  = @task.project
%p
  %b Description
  %br
    = @task.description
- if can? :update, @task
  = link_to 'Edit', edit_project_task_path(@task.project, @task)
  \|
= link_to 'All Tasks', project_tasks_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name  
  .field
    = f.label :email
    = f.email_field :email   
  - if can? :block, @user
    .field
      = f.label :blocked
      = f.check_box :blocked

  - if can? :edit_roles, @user
    - User::ROLES.each do |role|
      = role.capitalize
      = check_box_tag "user[roles][]",role, @user.role?(role)
  .actions
    = submit_tag 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1.b-title Listing users

%table.b-data-table
  %thead
    %tr
      %th Name
      %th Email
      %th{colspan: 3} Actions
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td
          - if can? :update, user
            = link_to 'Edit', edit_user_path(user)
        %td
          - if can? :destroy, user
            = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/users/show.html.haml
%h1.b-title
  User:
  = @user.name
  - if @user.blocked?
    %span.blocked-label (Blocked)
%p
  %b Email:
  = @user.email



= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/users/user_tasks.html.haml
/ %p.b-filter-project
/   = label :filter, :project_id
/   = collection_select(:filter, :project_id, current_user.projects, :id, :name, include_blank: 'All projects')


%h1.b-title 
  User: 
  = current_user.name

%p
  %b Email:
  = current_user.email

= render partial: 'tasks/tasks_table', locals: {tasks: @viewed_tasks}

= link_to 'New Project', new_project_path(:owner_id=>current_user)
\|
= link_to 'Projects', projects_path